### ISSUE TITLE
neopixel

### ISSUE THREAD

**Issue by ai2ik** [allocom/Rainbow-HAT#2]
sudo python demo.py
Traceback (most recent call last):
  File "demo.py", line 7, in <module>
    import rainbowhat as rainbow
  File "build/bdist.linux-armv7l/egg/rainbowhat.py", line 4, in <module>
ImportError: No module named neopixel

**Comment by kikura** [comment]
I'm also having this issue. Driving me nuts. Has anyone been able to fix this yet?

**Comment by sparkysbc** [comment]
at the end do installation of rpi-ws281x
/usr/src/rainbow-hat/library/rpi-ws281x# sudo python setup.py install
